# Generated by Django 3.1.1 on 2020-09-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookDoctor',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
