# Generated by Django 3.0.8 on 2020-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_auto_20200910_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='search',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
