# Generated by Django 3.0.8 on 2020-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_doctor_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='search',
        ),
        migrations.AddField(
            model_name='specialty',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
