# Generated by Django 3.0.8 on 2020-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_auto_20200911_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.AddField(
            model_name='specialty',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
