# Generated by Django 3.0.8 on 2020-09-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_auto_20200911_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_app.Specialty'),
        ),
    ]
